# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-13 00:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FSale', '0003_auto_20190413_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produk',
            name='aprice',
            field=models.IntegerField(default=150.0),
        ),
        migrations.AlterField(
            model_name='produk',
            name='brpice',
            field=models.IntegerField(default=210.0),
        ),
    ]
