# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-13 00:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FSale', '0004_auto_20190413_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produk',
            name='aprice',
            field=models.IntegerField(default=150000),
        ),
        migrations.AlterField(
            model_name='produk',
            name='brpice',
            field=models.IntegerField(default=210000),
        ),
    ]
