# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-13 00:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FSale', '0006_auto_20190413_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produk',
            name='after_price',
            field=models.CharField(default='150.000', max_length=50),
        ),
        migrations.AlterField(
            model_name='produk',
            name='before_price',
            field=models.CharField(default='210.000', max_length=50),
        ),
    ]
