# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-13 00:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FSale', '0007_auto_20190413_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='produk',
            name='url',
            field=models.CharField(default='www.google.com', max_length=255),
        ),
    ]
