# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-14 04:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FSale', '0010_auto_20190414_0425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produk',
            name='img',
            field=models.CharField(default='img/product/p1.jpg', max_length=1024),
        ),
        migrations.AlterField(
            model_name='produk',
            name='nama',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='produk',
            name='url',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
