# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-14 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FSale', '0011_auto_20190414_0444'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.CharField(default='0', max_length=2)),
                ('minute', models.CharField(default='0', max_length=2)),
                ('second', models.CharField(default='0', max_length=2)),
                ('toko', models.CharField(default='Tokopedia', max_length=255)),
            ],
        ),
    ]
